""" 
refs
"""
conf_dct = {
    'Chiefs': 'AFC',
    'Bills': 'AFC',
    'Patriots': 'AFC',
    'Browns': 'AFC',
    'Ravens': 'AFC',
    'Titans': 'AFC',
    'Chargers': 'AFC',
    'Colts': 'AFC',
    'Dolphins': 'AFC',
    'Broncos': 'AFC',
    'Steelers': 'AFC',
    'Jets': 'AFC',
    'Raiders': 'AFC',
    'Jaguars': 'AFC',
    'Bengals': 'AFC',
    'Texans': 'AFC',
    'Buccaneers': 'NFC',
    'Rams': 'NFC',
    'Packers': 'NFC',
    '49ers': 'NFC',
    'Seahawks': 'NFC',
    'Cowboys': 'NFC',
    'Saints': 'NFC',
    'Falcons': 'NFC',
    'Vikings': 'NFC',
    'Redskins': 'NFC',
    'Cardinals': 'NFC',
    'Bears': 'NFC',
    'Giants': 'NFC',
    'Panthers': 'NFC',
    'Eagles': 'NFC',
    'Lions': 'NFC',
    }

champ_hist = {
    2017: 'Jackson',
    2018: 'Brandon',
    2019: 'Jordan',
    2020: 'Alex',
    2021: 'Dan',
    }
